CREATE TABLE IF NOT EXISTS info(
CODIGO SERIAL PRIMARY KEY,
RAZAO_SOCIAL VARCHAR(120),
NOME_FANTASIA VARCHAR(120),
CNPJ CHAR(14),
TELEFONE VARCHAR(12),
LOGRADOURO VARCHAR(120),
NUMERO SMALLINT,
COMPLEMENTO VARCHAR(200),
ESTADO CHAR(2),
CEP VARCHAR(10),
DT_ABERTURA DATE

);